apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: changedetection
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  # - ingress.yaml     # uncomment if you want ingress

commonLabels:
  app.kubernetes.io/name: changedetection
  app.kubernetes.io/part-of: changedetection
