apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-datastore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # or your preferred storage class
