apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blinko

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  - sealedsecret.yaml
