apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedpushr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedpushr
  template:
    metadata:
      labels:
        app: feedpushr
    spec:
      containers:
        - name: feedpushr
          image: ncarlier/feedpushr
          ports:
            - containerPort: 80
