apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feedpushr
spec:
  rules:
    - host: feedpushr.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedpushr
                port:
                  number: 80