apiVersion: v1
kind: Service
metadata:
  name: feedpushr
spec:
  type: LoadBalancer
  selector:
    app: feedpushr
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Cluster
