apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-storage-pvc
spec:
  storageClassName: longhorn   # change if your StorageClass has a different name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi