apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-cert
  namespace: default
spec:
  secretName: adguard-tls
  issuerRef:
    name: home-ca-issuer
    kind: ClusterIssuer
  commonName: adguard.home
  dnsNames:
  - adguard.home