apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: ghcr.io/umami-software/umami:postgresql-latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: umami-config
                  key: DATABASE_TYPE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-secrets
                  key: DATABASE_URL
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: umami-secrets
                  key: APP_SECRET
          readinessProbe:
            httpGet:
              path: /api/heartbeat
              port: 80
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/heartbeat
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi