apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics
commonLabels:
  app.kubernetes.io/name: umami
  app.kubernetes.io/part-of: umami

resources:
  - namespace.yaml
  - configmap.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml
