apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-systems

helmCharts:
  - name: gha-runner-scale-set-controller
    releaseName: arc
    namespace: arc-systems
    repo: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller