apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  labels:
    app.kubernetes.io/component: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        runAsNonRoot: true
      containers:
        - name: blocky
          image: ghcr.io/0xerr0r/blocky:main
          imagePullPolicy: IfNotPresent
          args:
            - --config=/etc/blocky/config.yaml
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 4000  # metrics/UI if enabled
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/blocky
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_BIND_SERVICE"]   # bind to port 53 without root
              drop: ["ALL"]
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: blocky-config
