apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: feedpushr-cert
  namespace: default
spec:
  secretName: feedpushr-tls
  issuerRef:
    name: home-ca-issuer
    kind: ClusterIssuer
  commonName: sample.home
  dnsNames:
  - sample.home
