apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: media
              mountPath: /media
      volumes:
        - name: media
          hostPath:
            path: /mnt/nas
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: NodePort
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30096
  selector:
    app: jellyfin